CREATE TABLE GAMES_PLAYED(
   ID 			  INTEGER PRIMARY KEY,
   NAME           TEXT    NOT NULL UNIQUE,
   CHARACTER_ID   INT     NOT NULL 
);
CREATE INDEX games_played_name_idx ON GAMES_PLAYED (NAME);

CREATE TABLE CHARACTER(
   ID            INTEGER PRIMARY KEY,
   NAME          TEXT    NOT NULL UNIQUE,
   EXPERIENCE    INT     NOT NULL,
   WEAPON        TEXT
);
CREATE INDEX character_name_idx ON CHARACTER (NAME);
